language: node_js
node_js:
  - "6.10.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python3
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - cp ./config/test.config.template ./config/test.config
after_success:
  - rm ./config/test.config
before_deploy:
  - ./scripts/install/flyway.sh
  - pip3 install requests
  - TODO: create deps
  - cp ./config/prod.config.template ./config/prod.config
  - npm run prod-migrations
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $HACKILLINOIS_ACCESS_KEY_ID
  secret_access_key: $HACKILLINOIS_SECRET_ACCESS_KEY
  region: "us-east-2"
  app: "hackillinois-api"
  env: "api-hackillinois"
  bucket_name: $HACKILLINOIS_BUCKET_NAME
