language: node_js
sudo: required
node_js:
  - "6.11.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python3-pip
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - cp ./config/test.json.template ./config/test.json
before_deploy:
  - ./scripts/install/flyway.sh
  - ./scripts/install/deps.sh
  - cp ./config/prod.json.template ./config/prod.json
  - python3 ./scripts/deploy/deps.py
  - npm run prod-migrations
deploy:
  provider: elasticbeanstalk
  skip_cleanup: false
  access_key_id: $HACKILLINOIS_ACCESS_KEY_ID
  secret_access_key: $HACKILLINOIS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "hackillinois-api"
  env: "hackillinois-api"
  bucket_name: $HACKILLINOIS_BUCKET_NAME
