CREATE TABLE `endpoints` (
  `endpoint` VARCHAR(50) NOT NULL,
  `enabled` BIT(1),
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`endpoint`)
);
